package tim21.PortalVlasti.soap.service.request;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-06T00:24:44.814+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "RequestService", 
                  wsdlLocation = "classpath:wsdl/Request.wsdl",
                  targetNamespace = "http://www.zahtev.com") 
public class RequestService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.zahtev.com", "RequestService");
    public final static QName RequestServiceSoapBinding = new QName("http://www.zahtev.com", "RequestServiceSoapBinding");
    static {
        URL url = RequestService.class.getClassLoader().getResource("wsdl/Request.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RequestService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Request.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public RequestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequestService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RequestService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RequestService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RequestService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RequestServicePortType
     */
    @WebEndpoint(name = "RequestServiceSoapBinding")
    public RequestServicePortType getRequestServiceSoapBinding() {
        return super.getPort(RequestServiceSoapBinding, RequestServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestServicePortType
     */
    @WebEndpoint(name = "RequestServiceSoapBinding")
    public RequestServicePortType getRequestServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(RequestServiceSoapBinding, RequestServicePortType.class, features);
    }

}
