
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.PortalPoverenika.soap.service.appealDeclaration;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tim21.PortalPoverenika.model.appealDeclaration.IzjasnjavanjeZalba;
import tim21.PortalPoverenika.model.appealDeclaration.TIzjasnjavanjeZalbaDok;
import tim21.PortalPoverenika.service.AppealDeclarationService;
import tim21.PortalPoverenika.soap.dto.TResponse;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T20:03:23.843+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "DeclareAppealService",
                      portName = "DeclareAppealServiceSoapBinding",
                      targetNamespace = "http://www.izjasnjavanjezalba.com",
                      wsdlLocation = "classpath:wsdl/IzjasnjavanjeZalba.wsdl",
                      endpointInterface = "tim21.PortalPoverenika.soap.service.appealDeclaration.DeclareAppealServicePortType")
@Service
public class DeclareAppealServiceSoapBindingImpl implements DeclareAppealServicePortType {

    @Autowired
    AppealDeclarationService declarationService;

    private static final Logger LOG = Logger.getLogger(DeclareAppealServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.izjasnjavanjezalba.DeclareAppealServicePortType#declareAboutAppeal(com.izjasnjavanjezalba.TIzjasnjavanjeZalbaDok izjasnjavanjeZalbaDokument)*
     */
    public TResponse declareAboutAppeal(TIzjasnjavanjeZalbaDok izjasnjavanjeZalbaDokument) {
        LOG.info("Executing operation declareAboutAppeal");
        System.out.println(izjasnjavanjeZalbaDokument);
        try {
            TResponse response = new TResponse();
            response.setStatus("FAILED");
            //ovde sacuvaj deklaraciju i vrati ok
            IzjasnjavanjeZalba declarationRoot = new IzjasnjavanjeZalba();
            declarationRoot.setIzjasnjavanjeZalbaDokument(izjasnjavanjeZalbaDokument);

            IzjasnjavanjeZalba created = declarationService.create(declarationRoot);

            if (created != null) {
                response.setStatus("SUCCESS");
            }

            return response;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
