<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://www.zalbanaodluku.com"
                  xmlns:tns="http://www.zalbanaodluku.com"
                  name="DecisionAppealService">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.zalbanaodluku.com" schemaLocation="../xsd/zalbanaodluku.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="getDecisionAppealRequest">
        <wsdl:part name="id" type="xsd:string" />
    </wsdl:message>
    <wsdl:message name="getDecisionAppealResponse">
        <wsdl:part name="zalba_odluka" type="tns:TZalba" />
    </wsdl:message>

    <wsdl:portType name="DecisionAppealServicePortType">
        <wsdl:operation name="getDecisionAppealById">
            <wsdl:input message="tns:getDecisionAppealRequest" />
            <wsdl:output message="tns:getDecisionAppealResponse" />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="DecisionAppealServiceSoapBinding" type="tns:DecisionAppealServicePortType">
        <soap:binding style="rpc"  transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="getDecisionAppealById">
            <soap:operation soapAction="http://www.zalbanaodluku.com/ws/getDecisionAppealById" />
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="DecisionAppealService">
        <wsdl:port name="DecisionAppealServiceSoapBinding" binding="tns:DecisionAppealServiceSoapBinding">
            <soap:address location="http://localhost:8080/DecisionAppealPort" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>