PREFIX pred: <http://www.tim21.com/predicate/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?rescript FROM <http://localhost:8089/fuseki/Tim21Dataset/data/resenja>
WHERE{
    ?rescript pred:rescriptForAppeal ?rescriptForAppeal .
    ?rescript pred:rescriptDate ?rescriptDate .
    ?rescript pred:appealStatus ?appealStatus .
    ?rescript pred:commisionerName ?commisionerName .
    ?rescript pred:commisionerLastname ?commisionerLastname .
    ?rescript pred:submitter ?submitter

    FILTER(CONTAINS(UCASE(str(?rescriptForAppeal)), UCASE("%1$s"))
        && CONTAINS(UCASE(str(?rescriptDate)), UCASE("%2$s"))
        && CONTAINS(UCASE(str(?appealStatus)), UCASE("%3$s"))
        && CONTAINS(UCASE(str(?commisionerName)), UCASE("%4$s"))
        && CONTAINS(UCASE(str(?commisionerLastname)), UCASE("%5$s"))
    	&& CONTAINS(UCASE(str(?submitter)), UCASE("%6$s"))
    ).
}
