PREFIX pred: <http://www.tim21.com/predicate/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?id FROM <http://localhost:8089/fuseki/Tim21Dataset/data/zalbeCutanje>
WHERE{
    ?id pred:submitterStreet ?submitterStreet .
    ?id pred:submitterCity ?submitterCity .
    ?id pred:submitterName ?submitterName .
    ?id pred:submitterLastname ?submitterLastname .
    ?id pred:appealForRequest ?appealForRequest .
    ?id pred:requestDate ?requestDate .
    ?id pred:recipientStreet ?recipientStreet .
    ?id pred:recipientCity ?recipientCity .
    ?id pred:requestDetails ?requestDetails .
    ?id pred:authorityName ?authorityName .
    ?id pred:appealDate ?appealDate .


    FILTER(CONTAINS(UCASE(str(?submitterStreet)), UCASE("%1$s"))
        && CONTAINS(UCASE(str(?submitterCity)), UCASE("%2$s"))
        && CONTAINS(UCASE(str(?submitterName)), UCASE("%3$s"))
        && CONTAINS(UCASE(str(?submitterLastname)), UCASE("%4$s"))
        && CONTAINS(UCASE(str(?appealForRequest)), UCASE("%5$s"))
    	&& CONTAINS(UCASE(str(?requestDate)), UCASE("%6$s"))
    	&& CONTAINS(UCASE(str(?recipientStreet)), UCASE("%7$s"))
    	&& CONTAINS(UCASE(str(?recipientCity)), UCASE("%8$s"))
    	&& CONTAINS(UCASE(str(?requestDetails)), UCASE("%9$s"))
    	&& CONTAINS(UCASE(str(?authorityName)), UCASE("%10$s"))
    	&& CONTAINS(UCASE(str(?appealDate)), UCASE("%11$s"))

    ).
}
