package tim21.EmailApp.soap.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tim21.EmailApp.model.MailRequest;
import tim21.EmailApp.model.TResponse;
import tim21.EmailApp.service.EmailService;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T21:24:52.339+01:00
 * Generated source version: 3.2.1
 *
 */

@WebService(
        serviceName = "MailService",
        portName = "MailServiceSoapBinding",
        targetNamespace = "http://www.mail.com",
        wsdlLocation = "classpath:wsdl/Mail.wsdl",
        endpointInterface = "tim21.EmailApp.soap.service.MailServicePortType")
@Service
public class MailServiceSoapBindingImpl implements MailServicePortType {

    @Autowired
    EmailService emailService;

    private static final Logger LOG = Logger.getLogger(MailServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mail.MailServicePortType#sendEmail(com.mail.MailRequest mail)*
     */
    public TResponse sendEmail(MailRequest mail) {
        LOG.info("Executing operation sendEmail");
        System.out.println(mail);
        try {
            TResponse _return = emailService.sendMail(mail);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
