package tim21.EmailApp.soap.service;

import tim21.EmailApp.model.MailRequest;
import tim21.EmailApp.model.ObjectFactory;
import tim21.EmailApp.model.TResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T21:24:52.403+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.mail.com", name = "MailServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MailServicePortType {

    @WebMethod(action = "http://www.mail.com/ws/sendEmail")
    @WebResult(name = "result", targetNamespace = "", partName = "result")
    public TResponse sendEmail(
        @WebParam(partName = "mail", name = "mail", targetNamespace = "")
                MailRequest mail
    );
}
