package tim21.PortalPoverenika.soap.service.report;

import tim21.PortalPoverenika.model.report.ObjectFactory;
import tim21.PortalPoverenika.model.report.TIzvestaj;
import tim21.PortalPoverenika.model.report.TResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T15:35:33.168+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.izvestaj.com", name = "ReportServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReportServicePortType {

    @WebMethod(action = "http://www.izvestaj.com/ws/getAppealStats")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public TIzvestaj getAppealStats(
        @WebParam(partName = "year", name = "year", targetNamespace = "")
        int year
    );

    @WebMethod(action = "http://www.izvestaj.com/ws/submitReport")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public TResponse submitReport(
        @WebParam(partName = "izvestaj", name = "izvestaj", targetNamespace = "")
        TIzvestaj izvestaj
    );
}
