
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.PortalPoverenika.soap.service.report;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tim21.PortalPoverenika.model.report.TIzvestaj;
import tim21.PortalPoverenika.model.report.TResponse;
import tim21.PortalPoverenika.service.SilenceAppealService;
import tim21.PortalPoverenika.service.DecisionAppealService;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T15:35:33.008+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ReportService",
                      portName = "ReportServiceSoapBinding",
                      targetNamespace = "http://www.izvestaj.com",
                      wsdlLocation = "classpath:wsdl/Report.wsdl",
                      endpointInterface = "tim21.PortalPoverenika.soap.service.report.ReportServicePortType")

@Service
public class ReportServiceSoapBindingImpl implements ReportServicePortType {

    private static final Logger LOG = Logger.getLogger(ReportServiceSoapBindingImpl.class.getName());

    @Autowired
    DecisionAppealService decisionAppealService;

    @Autowired
    SilenceAppealService silenceAppealService;

    /* (non-Javadoc)
     * @see com.izvestaj.ReportServicePortType#getAppealStats(int year)*
     */
    public TIzvestaj getAppealStats(int year) {
        LOG.info("Executing operation getAppealStats");
        System.out.println(year);

        try {
            TIzvestaj res = new TIzvestaj();
            // izvlacenje
            return res;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.izvestaj.ReportServicePortType#submitReport(com.izvestaj.TIzvestaj izvestaj)*
     */
    public TResponse submitReport(TIzvestaj izvestaj) {
        LOG.info("Executing operation submitReport");
        System.out.println(izvestaj);
        try {
            TResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
