
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.PortalPoverenika.soap.service.rescript;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tim21.PortalPoverenika.model.lists.RescriptList;
import tim21.PortalPoverenika.model.rescript.ResenjeRoot;
import tim21.PortalPoverenika.model.rescript.TResenje;
import tim21.PortalPoverenika.service.RescriptService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T15:16:01.942+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "RescriptService",
                      portName = "RescriptServiceSoapBinding",
                      targetNamespace = "http://www.resenje.com",
                      wsdlLocation = "classpath:wsdl/Rescript.wsdl",
                      endpointInterface = "tim21.PortalPoverenika.soap.service.rescript.RescriptServicePortType")
@Service
public class RescriptServiceSoapBindingImpl implements RescriptServicePortType {

    private static final Logger LOG = Logger.getLogger(RescriptServiceSoapBindingImpl.class.getName());

    @Autowired
    RescriptService rescriptService;
    /* (non-Javadoc)
     * @see com.resenje.RescriptServicePortType#getAll()*
     */
    public RescriptList getAll() {
        LOG.info("Executing operation getAll");
        try {
            RescriptList _return = rescriptService.getAll();
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.resenje.RescriptServicePortType#getRescriptById(java.lang.String id)*
     */
    public TResenje getRescriptById(String id) {
        LOG.info("Executing operation getRescriptById");
        System.out.println(id);
        try {
            ResenjeRoot root = rescriptService.getOne(id);
            if (root != null) {
                return root.getResenje();
            }
           else {
                return null;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
