package tim21.PortalPoverenika.soap.service.rescript;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T15:16:01.963+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "RescriptService", 
                  wsdlLocation = "classpath:wsdl/Rescript.wsdl",
                  targetNamespace = "http://www.resenje.com") 
public class RescriptService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.resenje.com", "RescriptService");
    public final static QName RescriptServiceSoapBinding = new QName("http://www.resenje.com", "RescriptServiceSoapBinding");
    static {
        URL url = RescriptService.class.getClassLoader().getResource("wsdl/Rescript.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RescriptService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Rescript.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public RescriptService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RescriptService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RescriptService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RescriptService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RescriptService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RescriptService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RescriptServicePortType
     */
    @WebEndpoint(name = "RescriptServiceSoapBinding")
    public RescriptServicePortType getRescriptServiceSoapBinding() {
        return super.getPort(RescriptServiceSoapBinding, RescriptServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RescriptServicePortType
     */
    @WebEndpoint(name = "RescriptServiceSoapBinding")
    public RescriptServicePortType getRescriptServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(RescriptServiceSoapBinding, RescriptServicePortType.class, features);
    }

}
