package tim21.PortalVlasti.soap.service.rescript;

import tim21.PortalVlasti.soap.dto.rescript.TResenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T12:32:07.656+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.resenje.com", name = "RescriptServicePortType")
@XmlSeeAlso({tim21.PortalVlasti.soap.dto.rescript.ObjectFactory.class, tim21.PortalVlasti.model.shared.ObjectFactory.class, tim21.PortalVlasti.soap.dto.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RescriptServicePortType {

    @WebMethod(action = "http://www.resenje.com/ws/submitRescript")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public tim21.PortalVlasti.soap.dto.TResponse submitRescript(
        @WebParam(partName = "Resenje", name = "Resenje", targetNamespace = "")
                TResenje resenje
    );
}
