package tim21.PortalPoverenika.soap.service.silenceAppeal;

import tim21.PortalPoverenika.model.lists.SilenceAppealList;
import tim21.PortalPoverenika.model.silenceAppeal.ObjectFactory;
import tim21.PortalPoverenika.model.silenceAppeal.TZalbaCutanje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T12:51:09.329+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.zalbacutanje.com", name = "SilenceAppealServicePortType")
@XmlSeeAlso({tim21.PortalPoverenika.model.silenceAppeal.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SilenceAppealServicePortType {

    @WebMethod(action = "http://www.zalbacutanje.com/ws/getAll")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public SilenceAppealList getAll();

    @WebMethod(action = "http://www.zalbacutanje.com/ws/getSilenceAppealById")
    @WebResult(name = "zalba_cutanje", targetNamespace = "", partName = "zalba_cutanje")
    public TZalbaCutanje getSilenceAppealById(
        @WebParam(partName = "id", name = "id", targetNamespace = "")
        String id
    );
}
