
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.PortalPoverenika.soap.service.silenceAppeal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tim21.PortalPoverenika.model.lists.SilenceAppealList;
import tim21.PortalPoverenika.model.silenceAppeal.TZalbaCutanje;
import tim21.PortalPoverenika.model.silenceAppeal.ZalbaCutanjeRoot;
import tim21.PortalPoverenika.service.SilenceAppealService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-02T12:51:09.317+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "SilenceAppealService",
                      portName = "SilenceAppealServiceSoapBinding",
                      targetNamespace = "http://www.zalbacutanje.com",
                      wsdlLocation = "classpath:wsdl/SilenceAppeal.wsdl",
                      endpointInterface = "tim21.PortalPoverenika.soap.service.silenceAppeal.SilenceAppealServicePortType")
@Service
public class SilenceAppealServiceSoapBindingImpl implements SilenceAppealServicePortType {

    private static final Logger LOG = Logger.getLogger(SilenceAppealServiceSoapBindingImpl.class.getName());

    @Autowired
    SilenceAppealService silenceAppealService;
    /* (non-Javadoc)
     * @see com.zalbacutanje.SilenceAppealServicePortType#getAll()*
     */
    public SilenceAppealList getAll() {
        LOG.info("Executing operation getAll");
        try {
            SilenceAppealList _return = silenceAppealService.getAll();
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zalbacutanje.SilenceAppealServicePortType#getSilenceAppealById(java.lang.String id)*
     */
    public TZalbaCutanje getSilenceAppealById(String id) {
        LOG.info("Executing operation getSilenceAppealById");
        System.out.println(id);
        try {
            ZalbaCutanjeRoot root = silenceAppealService.getOne(id);
            if (root != null) {
                return root.getZalbaCutanje();
            }
            else {
                return null;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
