package tim21.PortalPoverenika.model.decisionAppeal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-31T23:02:17.492+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.zalbanaodluku.com", name = "DecisionAppealServicePortType")
@XmlSeeAlso({tim21.PortalPoverenika.model.decisionAppeal.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DecisionAppealServicePortType {

    @WebMethod(action = "http://www.zalbanaodluku.com/ws/getDecisionAppealById")
    @WebResult(name = "zalba_odluka", targetNamespace = "http://www.zalbanaodluku.com", partName = "zalba_odluka")
    public TZalba getDecisionAppealById(
        @WebParam(partName = "id", name = "id")
        String id
    );
}
