
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.PortalPoverenika.model.decisionAppeal;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-31T23:02:17.466+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "DecisionAppealService",
                      portName = "DecisionAppealServiceSoapBinding",
                      targetNamespace = "http://www.zalbanaodluku.com",
                      wsdlLocation = "classpath:wsdl/ZalbaNaOdluku.wsdl",
                      endpointInterface = "tim21.PortalPoverenika.model.decisionAppeal.DecisionAppealServicePortType")
                      
public class DecisionAppealServiceSoapBindingImpl implements DecisionAppealServicePortType {

    private static final Logger LOG = Logger.getLogger(DecisionAppealServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zalbanaodluku.DecisionAppealServicePortType#getDecisionAppealById(java.lang.String id)*
     */
    public TZalba getDecisionAppealById(String id) {
        LOG.info("Executing operation getDecisionAppealById");
        System.out.println(id);
        try {
            TZalba _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
