package tim21.PortalVlasti.soap.service.appealAnnouncement;

import tim21.PortalVlasti.model.appealAnnouncement.ObjectFactory;
import tim21.PortalVlasti.model.appealAnnouncement.TObZalbaDokument;
import tim21.PortalVlasti.soap.dto.TResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T16:06:54.682+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.zalbaobavestenje.com", name = "AppealAnnouncementServicePortType")
@XmlSeeAlso({ObjectFactory.class, tim21.PortalVlasti.soap.dto.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AppealAnnouncementServicePortType {

    @WebMethod(action = "http://www.zalbaobavestenje.com/ws/submitAppealAnnouncemenet")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public TResponse submitAppealAnnouncemenet(
        @WebParam(partName = "ObZalbaDokument", name = "ObZalbaDokument", targetNamespace = "")
                TObZalbaDokument obZalbaDokument
    );
}
