package tim21.PortalVlasti.soap.service.appealAnnouncement;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T16:06:54.682+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "AppealAnnouncementService", 
                  wsdlLocation = "classpath:wsdl/ObavestenjeZalba.wsdl",
                  targetNamespace = "http://www.zalbaobavestenje.com") 
public class AppealAnnouncementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.zalbaobavestenje.com", "AppealAnnouncementService");
    public final static QName AppealAnnoucServiceSoapBinding = new QName("http://www.zalbaobavestenje.com", "AppealAnnoucServiceSoapBinding");
    static {
        URL url = AppealAnnouncementService.class.getClassLoader().getResource("wsdl/ObavestenjeZalba.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AppealAnnouncementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/ObavestenjeZalba.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public AppealAnnouncementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppealAnnouncementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppealAnnouncementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AppealAnnouncementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AppealAnnouncementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AppealAnnouncementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AppealAnnouncementServicePortType
     */
    @WebEndpoint(name = "AppealAnnoucServiceSoapBinding")
    public AppealAnnouncementServicePortType getAppealAnnoucServiceSoapBinding() {
        return super.getPort(AppealAnnoucServiceSoapBinding, AppealAnnouncementServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppealAnnouncementServicePortType
     */
    @WebEndpoint(name = "AppealAnnoucServiceSoapBinding")
    public AppealAnnouncementServicePortType getAppealAnnoucServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(AppealAnnoucServiceSoapBinding, AppealAnnouncementServicePortType.class, features);
    }

}
