
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.PortalVlasti.soap.service.appealAnnouncement;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import tim21.PortalVlasti.model.appealAnnouncement.ObavestenjeZalba;
import tim21.PortalVlasti.model.appealAnnouncement.TObZalbaDokument;
import tim21.PortalVlasti.service.AppealAnnouncementService;
import tim21.PortalVlasti.soap.dto.TResponse;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T16:06:54.667+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "AppealAnnouncementService",
                      portName = "AppealAnnoucServiceSoapBinding",
                      targetNamespace = "http://www.zalbaobavestenje.com",
                      wsdlLocation = "classpath:wsdl/ObavestenjeZalba.wsdl",
                      endpointInterface = "tim21.PortalVlasti.soap.service.appealAnnouncement.AppealAnnouncementServicePortType")
 @Service
public class AppealAnnoucServiceSoapBindingImpl implements AppealAnnouncementServicePortType {

    @Autowired
    AppealAnnouncementService announcementService;

    private static final Logger LOG = Logger.getLogger(AppealAnnoucServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zalbaobavestenje.AppealAnnouncementServicePortType#submitAppealAnnouncemenet(com.zalbaobavestenje.TObZalbaDokument obZalbaDokument)*
     */
    public TResponse submitAppealAnnouncemenet(TObZalbaDokument obZalbaDokument) {
        LOG.info("Executing operation submitAppealAnnouncemenet");
        System.out.println(obZalbaDokument);
        TResponse response = new TResponse();
        response.setStatus("FAILED");
        try {
            ObavestenjeZalba announcement = new ObavestenjeZalba();
            announcement.setObZalbaDokument(obZalbaDokument);

            ObavestenjeZalba saved = announcementService.create(announcement);

            if (saved != null) {
                response.setStatus("SUCCESS");
            }


            return response;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
