package tim21.EmailApp.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T12:51:11.358+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.mail.com", name = "MailServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MailServicePortType {

    @WebMethod(action = "http://www.mail.com/ws/sendEmail")
    @WebResult(name = "success", targetNamespace = "http://www.mail.com", partName = "success")
    public String sendEmail(
        @WebParam(partName = "id", name = "id")
        MailRequest id
    );
}
