
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package tim21.EmailApp.model;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T12:51:11.332+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "MailService",
                      portName = "MailServiceSoapBinding",
                      targetNamespace = "http://www.mail.com",
                      wsdlLocation = "classpath:wsdl/Mail.wsdl",
                      endpointInterface = "com.mail.MailServicePortType")
                      
public class MailServiceSoapBindingImpl implements MailServicePortType {

    private static final Logger LOG = Logger.getLogger(MailServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mail.MailServicePortType#sendEmail(com.mail.MailRequest id)*
     */
    public String sendEmail(MailRequest id) {
        LOG.info("Executing operation sendEmail");
        System.out.println(id);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
